name: "sf_opportunities"
entities:
  - name: "account"
    properties:
      - name: "extId"
        type: "sequence"
        index:
          id: 0
      - name: "Name"
        type: "text"
        index:
          id: 1
      - name: "AccountNumber"
        type: "text"
      - name: "Active__c"
        type: "text"
      - name: "Fax"
        type: "text"
      - name: "Phone"
        type: "text"
      - name: "Rating"
        type: "text"
      - name: "Type"
        type: "text"
      - name: "BillingStreet"
        type: "text"
      - name: "BillingCity"
        type: "text"
      - name: "BillingState"
        type: "text"
      - name: "BillingCountry"
        type: "text"
      - name: "BillingPostalCode"
        type: "text"
      - name: "ShippingStreet"
        type: "text"
      - name: "ShippingCity"
        type: "text"
      - name: "ShippingState"
        type: "text"
      - name: "ShippingCountry"
        type: "text"
      - name: "ShippingPostalCode"
        type: "text"
